-- idol group table

CREATE TABLE `idol_group`
(
    `idol_group_id`       bigint(20) NOT NULL AUTO_INCREMENT,
    `gender`              varchar(255) DEFAULT NULL,
    `idol_group_name_eng` varchar(255) DEFAULT NULL,
    `idol_group_name_kr`  varchar(255) DEFAULT NULL,
    PRIMARY KEY (`idol_group_id`)
) ENGINE = InnoDB
  AUTO_INCREMENT = 147
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_general_ci;


INSERT INTO `idol_group`
VALUES (1, 'female', 'Girls\' Generation', '소녀시대'),
       (2, 'male', 'SHINee', '샤이니'),
       (3, 'male', 'EXO', '엑소'),
       (4, 'female', 'Red Velvet', '레드벨벳'),
       (5, 'male', 'NCT', '엔시티'),
       (6, 'male', 'NCT U', '엔시티 유'),
       (7, 'male', 'NCT 127', '엔시티 127'),
       (8, 'male', 'NCT DREAM', '엔시티 드림'),
       (9, 'male', 'NCT WISH', '엔시티 위시'),
       (10, 'female', 'aespa', '에스파'),
       (11, 'male', 'RIIZE', '라이즈'),
       (13, 'male', '2AM', '투에이엠'),
       (14, 'male', '2PM', '투피엠'),
       (16, 'male', 'GOT7', '갓세븐'),
       (18, 'male', 'DAY6', '데이식스'),
       (19, 'female', 'TWICE', '트와이스'),
       (20, 'male', 'Stray Kids', '스트레이 키즈'),
       (21, 'female', 'ITZY', '있지'),
       (22, 'male', 'Xdinary Heroes', '엑스디너리 히어로즈'),
       (23, 'female', 'NMIXX', '엔믹스'),
       (25, 'male', 'WINNER', '위너'),
       (26, 'male', 'iKON', '아이콘'),
       (27, 'female', 'BLACKPINK', '블랙핑크'),
       (28, 'male', 'TREASURE', '트레저'),
       (29, 'male', 'PLAVE', '플레이브'),
       (30, 'male', 'BTS', '방탄소년단'),
       (31, 'male', 'TXT', '투모로우바이투게더'),
       (35, 'male', 'MIRAE', '미래소년'),
       (36, 'female', '4Minute', '포미닛'),
       (37, 'male', 'HIGHLIGHT', '하이라이트'),
       (38, 'male', 'BTOB', '비투비'),
       (40, 'male', 'Pentagon', '펜타곤'),
       (41, 'female', '(G)I-DLE', '(여자)아이들'),
       (42, 'female', 'LIGHTSUM', '라잇썸'),
       (43, 'female', 'GFriend', '여자친구'),
       (44, 'female', 'LE SSERAFIM', '르세라핌'),
       (45, 'female', 'NewJeans', '뉴진스'),
       (46, 'male', 'The Boyz', '더보이즈'),
       (47, 'female', 'Apink', '에이핑크'),
       (48, 'male', 'VICTON', '빅톤'),
       (50, 'female', 'Weeekly', '위클리'),
       (51, 'male', 'ATBO', '앳보'),
       (52, 'male', 'FT Island', 'FT아일랜드'),
       (53, 'male', 'CNBLUE', '씨엔블루'),
       (55, 'male', 'N.Flying', '엔플라잉'),
       (56, 'male', 'SF9', '에스에프나인'),
       (57, 'female', 'Cherry Bullet', '체리블렛'),
       (58, 'male', 'P1Harmony', '피원하모니'),
       (63, 'male', 'ASTRO', '아스트로'),
       (64, 'female', 'Weki Meki', '위키미키'),
       (67, 'male', 'NU\'EST', '뉴이스트'),
       (68, 'male', 'SEVENTEEN', '세븐틴'),
       (70, 'female', 'fromis_9', '프로미스나인'),
       (71, 'male', 'TWS', '투어스'),
       (72, 'female', 'IU', '아이유'),
       (76, 'female', 'CLASS:y', '클라씨'),
       (77, 'male', 'FANTASY BOYS', '판타지 보이즈'),
       (83, 'male', 'DKB', '다크비'),
       (88, 'male', 'CIX', '씨아이엑스'),
       (89, 'male', 'EPEX', '이펙스'),
       (93, 'male', 'Boyfriend', '보이프렌드'),
       (94, 'male', 'Monsta X', '몬스타엑스'),
       (95, 'female', 'WJSN', '우주소녀'),
       (96, 'male', 'CRAVITY', '크래비티'),
       (97, 'female', 'IVE', '아이브'),
       (100, 'female', 'Dreamcatcher', '드림캐쳐'),
       (101, 'male', 'DRIPPIN', '드리핀'),
       (109, 'male', 'ATEEZ', '에이티즈'),
       (110, 'male', 'xikers', '싸이커스'),
       (115, 'male', 'UP10TION', '업텐션'),
       (123, 'female', 'EVERGLOW', '에버글로우'),
       (124, 'male', 'TEMPEST', '템페스트'),
       (125, 'female', 'Chungha', '청하'),
       (127, 'male', 'IN2IT', '인투잇'),
       (128, 'female', 'MOMOLAND', '모모랜드'),
       (129, 'female', 'IZ*ONE', '아이즈원'),
       (133, 'female', 'LOONA', '이달의 소녀'),
       (135, 'male', 'AB6IX', '에이비식스'),
       (137, 'male', 'YOUNITE', '유나이트'),
       (138, 'male', 'GHOST9', '고스트나인'),
       (139, 'male', 'ENHYPEN', '엔하이픈'),
       (141, 'female', 'Isekai Idol', '이세계 아이돌'),
       (142, 'male', 'NINE.i', '나인아이'),
       (143, 'female', 'Queenz Eye', '퀸즈아이'),
       (144, 'male', 'TOZ', '토즈'),
       (145, 'male', 'ONE PACT', '원팩트'),
       (146, 'male', 'TIOT', '티아이오티');